import Nav from './components/Nav'
import '../globals.css'
import Footer from './components/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"  className="scroll-smooth">
      
      <body className="max-w-screen-2xl mx-auto scroll-smooth">
      <Nav />
      <div>
        {children}
      </div> 
      {/* @ts-expect-error Server Component */}
        <Footer/>
      </body>
    </html>
  )
}
