import Nav from './components/Nav'
import '../globals.css'
import Footer from './components/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"  >
      
      <body className="max-w-screen-2xl  mx-auto scroll-smooth box-border ">
        {/* @ts-expect-error Server Component */}
      <Nav />
      <div className=' min-h-screen md:min-h-[700px] lg:min-h-[800px]'>
        {children}
      </div> 
      {/* @ts-expect-error Server Component */}
        <Footer/>
      </body>
    </html>
  )
}
