
// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
//   }

import { Suspense } from "react"

  
  export default function GalleryLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <section className="min-h-full">
          
            {children}
           
        </section>
    )
  }
  